[build]
 command = "npm run build"
 publish = "out"

[dev]
 command = "npm run dev"
 port = 3000

[build.environment]
 NODE_VERSION = "14"

[[redirects]]
 from = "/*"
 to = "/index.html"
 status = 200